### ISSUE TITLE
aws:ec2:Instance yaml example didn't work

### ISSUE THREAD

**Issue by dixler** [pulumi/registry#1569]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/instance/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/instance/)

```
Previewing update (dev)

View Live: https://app.pulumi.com/dixler/aws-ec2-instance/dev/previews/664d0b5f-7381-480b-9566-f722e22c8b09

     Type                 Name                  Plan       Info
 +   pulumi:pulumi:Stack  aws-ec2-instance-dev  create     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (aws-ec2-instance-dev):
    error: rpc error: code = Unknown desc = invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
    	* InvalidUserID.Malformed: Invalid user id: "99720109477"
    	status code: 400, request id: e64b5b67-8688-442a-86ac-e25da7145c21
    
    
    
      on Pulumi.yaml line 14:
      14:     Fn::Invoke:
      15:       Function: aws:ec2:getAmi
      16:       Arguments:
      17:         mostRecent: true
      18:         filters:
      19:           - name: name
      20:             values:
      21:               - ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
      22:           - name: virtualization-type
      23:             values:
      24:               - hvm
      25:         owners:
      26:           - 099720109477
    error: Error registering variable [ubuntu]: Pulumi.yaml:14,5-26,25: rpc error: code = Unknown desc = invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
    	* InvalidUserID.Malformed: Invalid user id: "99720109477"
    	status code: 400, request id: e64b5b67-8688-442a-86ac-e25da7145c21

```

**Comment by lukehoban** [comment]
I see we now generate this quoted - which should address the issue:

```yaml
resources:
  web:
    type: aws:ec2:Instance
    properties:
      ami: ${ubuntu.id}
      instanceType: t3.micro
      tags:
        Name: HelloWorld
variables:
  ubuntu:
    fn::invoke:
      Function: aws:ec2:getAmi
      Arguments:
        mostRecent: true
        filters:
          - name: name
            values:
              - ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
          - name: virtualization-type
            values:
              - hvm
        owners:
          - '099720109477'
```
