### ISSUE TITLE
YAML ec2 example broken

### ISSUE THREAD

**Issue by dixler** [pulumi/registry#1652]
File: [themes/default/content/registry/packages/aws/api-docs/ec2/instance/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/instance/)

```yaml
resources:
  web:
    type: aws:ec2:Instance
    properties:
      ami: ${ubuntu.id}
      instanceType: t3.micro
      tags:
        Name: HelloWorld
variables:
  ubuntu:
    Fn::Invoke:
      Function: aws:ec2:getAmi
      Arguments:
        mostRecent: true
        filters:
          - name: name
            values:
              - ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
          - name: virtualization-type
            values:
              - hvm
        owners:
          - 099720109477
```

`099720109477` is interpreted as an integer and the `0` is dropped causing the AMI lookup to fail.
