### ISSUE TITLE
It seems that the `apiClientLogging` property can no longer be passed to the provider in YAML

### ISSUE THREAD

**Issue by yuripallada-groupm** [pulumi/registry#7506]
File: [themes/default/content//registry/packages/cloudflare](https://www.pulumi.com/registry/packages/cloudflare/)

We have this code:
```
  cloudflare-provider:
    type: pulumi:providers:cloudflare
    properties:
      apiToken: ${token}
      apiClientLogging: true
```

When we try to apply this using our pipeline, Pulumi shows this error:
```
